# Generated by Django 3.0.3 on 2020-05-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='student_applied',
            field=models.ManyToManyField(blank=True, null=True, related_name='applied_Student', to='User_Profile.Student', verbose_name='申请学员'),
        ),
    ]
