# Generated by Django 3.0.4 on 2020-05-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('User_Profile', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='User_Profile.Student'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='User_Profile.Teacher'),
        ),
    ]
