# Generated by Django 3.1 on 2020-05-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20200520_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='grade_course',
            field=models.CharField(choices=[('0', '小学一年级至三年级'), ('1', '小学四年级至六年级'), ('2', '初一'), ('3', '初二'), ('4', '初三'), ('5', '高一'), ('6', '高二'), ('7', '高三'), ('8', '其他')], max_length=2, verbose_name='学生年级'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='introduction',
            field=models.CharField(default='', max_length=150, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='subject',
            field=models.CharField(choices=[('zh', '语文'), ('math', '数学'), ('en', '英语'), ('phy', '物理'), ('che', '化学'), ('bio', '生物'), ('pol', '政治'), ('his', '历史'), ('geo', '地理')], max_length=10, verbose_name='科目'),
        ),
    ]
