# Generated by Django 3.0.3 on 2020-05-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0001_initial'),
        ('Course', '0002_auto_20200520_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='student_applied',
            field=models.ManyToManyField(blank=True, related_name='applied_Student', to='User_Profile.Student', verbose_name='申请学员'),
        ),
    ]
