# Generated by Django 3.0.4 on 2020-05-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Course', '0002_auto_20200522_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='comment',
            field=models.CharField(blank=True, default='暂无', max_length=100, null=True, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
