# Generated by Django 3.0.4 on 2020-05-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Course', '0004_auto_20200525_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='nick_name',
            field=models.CharField(max_length=50, verbose_name='课程名称'),
        ),
    ]
