# Generated by Django 3.0.3 on 2020-04-17 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=2)),
                ('grade', models.CharField(choices=[('0', '小学一年级至三年级'), ('1', '小学四年级至六年级'), ('2', '初一'), ('3', '初二'), ('4', '初三'), ('5', '高一'), ('6', '高二'), ('7', '高三'), ('8', '其他')], max_length=2)),
                ('mailbox', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('student_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=2)),
                ('grade', models.CharField(choices=[('0', '大一'), ('1', '大二'), ('2', '大三'), ('3', '大四'), ('4', '研一'), ('5', '研二'), ('6', '研三'), ('7', '其他')], max_length=2)),
                ('mailbox', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('student_teached', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User_Profile.Student')),
                ('teacher_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
