# Generated by Django 3.1 on 2020-04-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[('0', '小学一年级至三年级'), ('1', '小学四年级至六年级'), ('2', '初一'), ('3', '初二'), ('4', '初三'), ('5', '高一'), ('6', '高二'), ('7', '高三'), ('8', '其他')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='grade',
            field=models.IntegerField(choices=[('0', '大一'), ('1', '大二'), ('2', '大三'), ('3', '大四'), ('4', '研一'), ('5', '研二'), ('6', '研三'), ('7', '其他')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='student_teached',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User_Profile.Student'),
        ),
    ]
