# Generated by Django 3.0.4 on 2020-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('User_Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
