# Generated by Django 3.1 on 2020-05-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0002_auto_20200520_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '家教'},
        ),
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatar/%Y/%m/%d/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='student',
            name='briefintroduction',
            field=models.CharField(blank=True, help_text='个人简介，所在学校/学习情况等', max_length=100, null=True, verbose_name='教师信息'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatar/%Y/%m/%d/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='briefintroduction',
            field=models.CharField(blank=True, help_text='个人简介，所在学院/专业/履历等', max_length=100, null=True, verbose_name='教师信息'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('0', '小学一年级至三年级'), ('1', '小学四年级至六年级'), ('2', '初一'), ('3', '初二'), ('4', '初三'), ('5', '高一'), ('6', '高二'), ('7', '高三'), ('8', '其他')], default='5', max_length=2, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mailbox',
            field=models.EmailField(max_length=254, verbose_name='个人邮箱'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=' ', max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=20, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.CharField(choices=[('0', '大一'), ('1', '大二'), ('2', '大三'), ('3', '大四'), ('4', '研一'), ('5', '研二'), ('6', '研三'), ('7', '其他')], default='1', max_length=2, verbose_name='教师年级'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mailbox',
            field=models.EmailField(max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='联系电话'),
        ),
    ]
