# Generated by Django 3.0.3 on 2020-05-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0003_auto_20200428_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student_teached',
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
