# Generated by Django 3.0.4 on 2020-04-21 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('User_Profile', '0004_auto_20200419_2332'),
        ('User_Profile', '0002_auto_20200420_1110'),
    ]

    operations = [
    ]
